import { Playfair_Display, Poppins } from "next/font/google";
import "./globals.css";
import Header from "../Component/Header";
import Sidebar from "@/Component/Sidebar";

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${playfair.variable} ${poppins.variable}`}>
      <body className={`${poppins.className} min-h-full flex flex-col`}>
        <div>
          <Header />
        </div>

        <div className="flex flex-row gap-1">
          <div className="w-[15%]">
            <Sidebar />
          </div>
          <div className="w-[85%]">{children}</div>
        </div>
      </body>
    </html>
  );
}
