import { NextResponse } from "next/server";
import mongoose from "mongoose";
import connectMongoDB from "@/lib/databse/mongodb";
import Product from "@/lib/models/Product";
import Offer from "@/lib/models/Offer";
import { getAuthenticatedUser,isCustomer } from "@/lib/auth";
import { calculateTax,getTaxSettings } from "@/lib/tax";
export const dynamic="force-dynamic";
export async function POST(request){const user=await getAuthenticatedUser(request);if(!user)return NextResponse.json({message:"Authentication required"},{status:401});if(!isCustomer(user))return NextResponse.json({message:"Customer account required"},{status:403});try{const body=await request.json();const items=body.items;if(!Array.isArray(items)||items.length===0||items.length>50)return NextResponse.json({message:"Cart is empty or invalid"},{status:400});const ids=items.map(i=>i.id||i.productId);if(ids.some(id=>!mongoose.isValidObjectId(id)))return NextResponse.json({message:"Invalid product id"},{status:400});await connectMongoDB();const rows=await Product.find({_id:{$in:ids},isActive:true}).populate("category","categoryName").lean();const byId=new Map(rows.map(p=>[p._id.toString(),p]));let subtotal=0;const lines=[];for(const item of items){const p=byId.get(String(item.id||item.productId));const quantity=Number(item.quantity);if(!p)return NextResponse.json({message:"A product is unavailable"},{status:409});if(!Number.isInteger(quantity)||quantity<1||quantity>10)return NextResponse.json({message:"Quantity must be from 1 to 10"},{status:400});if(Number(p.currentStock||0)<quantity)return NextResponse.json({message:p.productName+" has insufficient stock"},{status:409});const price=Math.max(0,Number(p.price)*(1-Number(p.discount||0)/100));subtotal+=price*quantity;lines.push({id:p._id.toString(),name:p.productName,sku:p.productSKU,category:p.category?.categoryName||"",image:p.image?.url||"",price,quantity,stock:p.currentStock,discount:Number(p.discount||0)});}
let discount=0,offer=null;const coupon=String(body.couponCode||"").trim().toUpperCase();if(coupon){offer=await Offer.findOne({offerCode:coupon}).lean();const now=new Date();if(!offer||!offer.isActive||now<offer.startDate||now>offer.endDate||(offer.usageLimit&&offer.usageCount>=offer.usageLimit)||subtotal<(offer.minPurchase||0))return NextResponse.json({message:"This coupon is invalid or unavailable"},{status:400});if(offer.applyTo==="Specific Products"&&lines.some(line=>!offer.products.some(id=>id.toString()===line.id)))return NextResponse.json({message:"This coupon does not apply to every cart item"},{status:400});if(offer.perCustomerLimit&&await (await import("@/lib/models/Order")).default.countDocuments({customerUser:user._id,"financials.promotionCode":coupon})>=offer.perCustomerLimit)return NextResponse.json({message:"This coupon has reached its usage limit"},{status:400});discount=Math.min(offer.discountType==="Percentage"?subtotal*offer.discountValue/100:offer.discountValue,offer.maxDiscountAmount||Number.MAX_SAFE_INTEGER,subtotal);}
const settings=await getTaxSettings();const tax=calculateTax(Math.max(0,subtotal-discount),settings);const shipping=subtotal<75?12:0;const total=Math.max(0,subtotal-discount+(settings.inclusive?0:tax.tax)+shipping);return NextResponse.json({success:true,items:lines,subtotal:Number(subtotal.toFixed(2)),discount:Number(discount.toFixed(2)),tax:Number(tax.tax.toFixed(2)),taxName:tax.taxName||settings.name||"Tax",shipping,total:Number(total.toFixed(2)),couponCode:offer?.offerCode||"",paymentMethods:["Cash"]});}catch(error){console.error("Checkout quote error",error);return NextResponse.json({message:"Unable to calculate checkout totals"},{status:500});}}
